import type React from "react"
import type { Metadata } from "next"
import { Silkscreen } from "next/font/google"
import "./globals.css"
import Header from "@/components/header"
import Footer from "@/components/footer"

const silkscreen = Silkscreen({
  weight: "400",
  variable: "--font-silkscreen",
  subsets: ["latin"],
})
const silkscreenMono = Silkscreen({
  weight: "400",
  variable: "--font-silkscreen-mono",
  subsets: ["latin"],
})


export const metadata: Metadata = {
  title: "Human vs AI",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
          <body className={`${silkscreen.className} ${silkscreenMono.className} antialiased flex flex-col min-h-screen`}>
        <Header />
        <main className="flex-1 container mx-auto px-4 sm:px-6 lg:px-8 py-8">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
